name: fishing-bot-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - pillow
  - pip
  - pip:
    - ultralytics
    - customtkinter
    - pyautogui
    - pyinstaller
    
